language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-23.0.3
    - android-23

script: ./gradlew gradle -PBINTRAY_USER="" -PBINTRAY_KEY="" build